version: '3.3'

services:
  csgo:
    image: registry.teamzone.se/csgo/csgo-lan:0.1
    volumes:
      - /data/csgo/cfg/esl5on5.cfg:/server/csgo/csgo/cfg/esl5on5.cfg
      - /data/csgo/cfg/server.cfg:/server/csgo/csgo/cfg/server.cfg
      - /data/csgo/cfg/gamemode_competitive_server.cfg:/server/csgo/csgo/cfg/gamemode_competitive_server.cfg
      - /data/csgo/cfg/gotv.cfg:/server/csgo/csgo/cfg/gotv.cfg
    restart: always
    environment:
      HOSTNAME: wallhacktest
      MAP: de_dust2
      RCON: 123
    deploy:
      placement:
          constraints: [node.role == worker]

networks:
  default:
    external:
      name: swarm-macvlan
