version: '3.3'

services:
  csgo:
    image: soren90/csgo-lan:0.1
    stdin_open: true
    tty: true
    volumes:
      - /data/csgo/cfg/esl5on5.cfg:/server/csgo/csgo/cfg/esl5on5.cfg
      - /data/csgo/cfg/server.cfg:/server/csgo/csgo/cfg/server.cfg
      - /data/csgo/cfg/gamemode_competitive_server.cfg:/server/csgo/csgo/cfg/gamemode_competitive_server.cfg
      - /data/csgo/cfg/gotv.cfg:/server/csgo/csgo/cfg/gotv.cfg
      - /data/csgo/addons:/server/csgo/csgo/addons
    restart: always
    environment:
      HOSTNAME: Wallhack
      MAP: de_dust2
      RCON: phetto
    deploy:
#      resources:
#        reservations:
#          memory: 13G
      placement:
          constraints: [node.labels.usage==game]

networks:
  default:
    external:
      name: swarm-macvlan
