version: '3.3'

services:
  minecraft:
    image: rlenferink/minecraft
#    volumes:
#      - /data/minecraft:/data 
    restart: always
    deploy:
      placement:
          constraints: [node.labels == compute]

networks:
  default:
    external:
      name: swarm-macvlan
